In [1]:
import numpy as np
import pandas as pd

In [3]:
data = pd.read_csv('customer.csv')
data.head()

   age  gender   review education purchased
0   41    Male  Average        UG       Yes
1   29  Female     Good        PG       Yes
2   63    Male     Poor    School        No
3   52  Female  Average        UG        No
4   21    Male     Good    School       Yes

In [4]:
df = data.iloc[: , 2:]
df.head()

    review education purchased
0  Average        UG       Yes
1     Good        PG       Yes
2     Poor    School        No
3  Average        UG        No
4     Good    School       Yes

In [5]:
x=df.iloc[:,:2]
y=df.iloc[: , -1]

from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(x , y , test_size = 0.2)

In [6]:
from sklearn.preprocessing import OrdinalEncoder
od = OrdinalEncoder(categories=[['Poor' , 'Average','Good'],['School' , 'UG','PG']])