In [39]:
import numpy as np
import pandas as pd

In [40]:
dataset=pd.read_csv('data.csv')
dataset

      country   age   salary purchase
0         USA  25.0  50000.0     True
1       India  30.0      NaN    False
2          UK   NaN  70000.0     True
3      France  45.0      NaN    False
4      France  35.0  65000.0      NaN
5         NaN  40.0  62000.0     True
6       Japan  28.0  55000.0    False
7   Australia  33.0      NaN     True
8      Canada   NaN  58000.0    False
9       India   NaN  60000.0     True
10         UK  29.0  54000.0    False
11      China  42.0      NaN     True
12      India   NaN  68000.0      NaN
13      Japan  37.0      NaN    False
14      China  31.0  63000.0     True

## Independent varibales are -> country , age , salary
## dependent variable - > phurchase

In [41]:
# dataset.age.dtype='int'
# dataset.salary.dtype='int' --> wrong way
# dataset['age']=dataset['age'].astype(int)
# dataset['salary']=dataset['salary'].astype(int)
x=dataset[['country' , 'age' , 'salary']].values
x
x[:,1:3]=x[:,1:3].astype(float)

In [42]:
y=dataset['purchase'].values
y

array([True, False, True, False, nan, True, False, True, False, True,
       False, True, nan, False, True], dtype=object)

In [43]:
age_mean = np.nanmean(x[:,1])
age_mean

np.float64(34.09090909090909)

In [44]:
salary_mean=np.nanmean(x[:,2])
salary_mean

np.float64(60500.0)

In [45]:
country_mode = dataset['country'].mode().iloc[0]

In [46]:
purchase_mode = dataset['purchase'].mode().iloc[0]

## set the means to the nan of dataframe

In [47]:
dataset['age']=dataset['age'].fillna(age_mean)
dataset['salary']=dataset['salary'].fillna(salary_mean)
dataset['country']=dataset['country'].fillna(country_mode)
dataset['purchase']=dataset['purchase'].fillna(purchase_mode)

C:\Users\anime\AppData\Local\Temp\ipykernel_13956\2505740980.py:4: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  dataset['purchase']=dataset['purchase'].fillna(purchase_mode)

In [48]:
dataset['age']=dataset['age'].astype(int)
dataset['salary']=dataset['salary'].astype(int)

In [49]:
dataset

      country  age  salary  purchase
0         USA   25   50000      True
1       India   30   60500     False
2          UK   34   70000      True
3      France   45   60500     False
4      France   35   65000      True
5       India   40   62000      True
6       Japan   28   55000     False
7   Australia   33   60500      True
8      Canada   34   58000     False
9       India   34   60000      True
10         UK   29   54000     False
11      China   42   60500      True
12      India   34   68000      True
13      Japan   37   60500     False
14      China   31   63000      True

In [50]:
x=dataset[['country' , 'age' , 'salary']].values
x

array([['USA', 25, 50000],
       ['India', 30, 60500],
       ['UK', 34, 70000],
       ['France', 45, 60500],
       ['France', 35, 65000],
       ['India', 40, 62000],
       ['Japan', 28, 55000],
       ['Australia', 33, 60500],
       ['Canada', 34, 58000],
       ['India', 34, 60000],
       ['UK', 29, 54000],
       ['China', 42, 60500],
       ['India', 34, 68000],
       ['Japan', 37, 60500],
       ['China', 31, 63000]], dtype=object)

In [51]:
y=dataset['purchase'].values
y

array([ True, False,  True, False,  True,  True, False,  True, False,
        True, False,  True,  True, False,  True])